version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: my-portfolio-container
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge